---
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/retry/main.go
    flags:
    - -trimpath
    ldflags:
    - -s -w -extldflags "-static" -X github.com/homeport/retry/internal/cmd.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
- replacements:
    darwin: darwin
    linux: linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "{{.ProjectName}} release v{{.Version}}"

brews:
  - tap:
      owner: homeport
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/homeport/retry/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: GoReleaser Bot
      email: goreleaser@carlosbecker.com
    folder: HomebrewFormula
    homepage: "https://github.com/homeport/retry"
    description: "Tool to retry a command in case it fails"
    license: "MIT"
    skip_upload: false
    test: |
      system "#{bin}/retry --version"
